### ISSUE TITLE
Either build for other architectures, or provide a nodeSelector

### ISSUE THREAD

**Issue by darac** [smizy/charts#10]
Currently, [smizy/mosquitto](https://hub.docker.com/r/smizy/mosquitto) is only built for the `amd64` architecture. This means that, when deploying to a heterogeneous architecture cluster (e.g. AMD64 + ARM64), sometimes the wrong node is selected.

Please, either expand your CI/CD pipeline to build for additional architectures (ARM64, e.g. Raspberry Pis are becoming quite popular, as are other ARM solutions such as Amazon's Graviton processor), or add the following to the deployment.yaml:

```yaml
spec:
   ...
   ...
   containers:
     - name: ...
       ...
  nodeSelector:
    beta.kubernetes.io/arch: amd64
  volumes:
   - name: ...
     ...
```
This will ensure that mosquitto is only deployed to nodes with the correct architecture.

Thank you.
