### ISSUE TITLE
No ClusterIP is assigned when installing mosquitto with the chart here

### ISSUE THREAD

**Issue by rajasiman** [smizy/charts#4]
Command:
`helm install mosquitto-garden -f mosquitto.yaml --set nodeSelector.mqtt=mosquitto smizy/mosquitto`

I install mosquitto with the chart provided and I see that there is no ClusterIP assigned to this service. I have to manually expose the service in order to get a ClusterIP. 

Command for exposing the service: 
kubectl expose pod ll mosquitto-garden... --port=1883 --target-port=1883

> mosquitto.yaml
```
# Default values for mosquitto.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image: smizy/mosquitto:1.4.15-alpine

imagePullPolicy: IfNotPresent

service:
  enabled: true
  type: ClusterIP


persistence:
  enabled: false
  accessMode: ReadWriteOnce
  size: 1Gi
  storageClass: local

deployment:
  hostNetwork: false
  probes:
    livenessProbe:
      tcpSocket:
        port: 9090
      initialDelaySeconds: 5
      periodSeconds: 1
    readinessProbe:
      tcpSocket:
        port: 9090
      initialDelaySeconds: 3
      periodSeconds: 3
  resources:
    requests:
      cpu: 50m
      memory: 100Mi
    limits:
      cpu: 100m
      memory: 256Mi

config: |-
  log_dest stdout
  listener 1883
  listener 9090
  protocol websockets
```
i also tried adding the port and target port in the yaml file and installing it, but there was no change. 

Could you please help me?

Thank you.
